// JavaScript Document
jQuery(document).ready(function() {
	jQuery(".eTimer").eTimer({
		etType: 0, 
		etDate: "22.02.2020.11.0", 
		etTitleSize: 0, 
		etShowSign: 0, 
		etSep: ":", 
		etFontFamily: "Roboto", 
		etTextColor: "#44696c", 
		etPaddingTb: 10,
		etPaddingLR: 10, 
		etBackground: "white", 
		etBorderSize: 0, 
		etBorderRadius: 2, 
		etBorderColor: "white", 
		etLastUnit: 3, 
		etNumberFontFamily: "Roboto", 
		etNumberSize: 35, 
		etNumberColor: "#44696c", 
		etNumberPaddingTB: 0, 
		etNumberPaddingLR: 8, 
		etNumberBackground: "white", 
		etNumberBorderSize: 0, 
		etNumberBorderRadius: 0, 
		etNumberBorderColor: "#040303", 
	});
	jQuery(".nstTimer").eTimer({
		etType: 0, 
		etDate: "20.02.2020.4.0", 
		etTitleSize: 0, 
		etShowSign: 0, 
		etSep: ":", 
		etFontFamily: "Roboto", 
		etTextColor: "#44696c", 
		etPaddingTb: 10,
		etPaddingLR: 10, 
		etBackground: "white", 
		etBorderSize: 0, 
		etBorderRadius: 2, 
		etBorderColor: "white", 
		etLastUnit: 3, 
		etNumberFontFamily: "Roboto", 
		etNumberSize: 35, 
		etNumberColor: "#44696c", 
		etNumberPaddingTB: 0, 
		etNumberPaddingLR: 8, 
		etNumberBackground: "white", 
		etNumberBorderSize: 0, 
		etNumberBorderRadius: 0, 
		etNumberBorderColor: "#040303", 
	});
});